import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import Link from 'next/link'
import Navbar from './component/navbar'
import useTranslation from "next-translate/useTranslation";

export default function Home() {
 
  let { t } = useTranslation();
  
 
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       
       <h1>
        {t("about:title")}
       </h1>
     
      <Navbar/>
      </main>

      
    </div>
  )
}
